Qmski presentation
ormir-mids/ormir-mids pull request #11
Opened 2024-10-24 16:05 UTC by simoneponcioni

Hi all,

In this PR, I modified the following:

    I prepared the preliminary version of the two notebooks for the QMSKI workshop 2024.
    I updated, as discussed, all instances of MedicalVolume, that are now imported from by voxel.

With a few adjustments left, the notebooks are almost ready for the WS. @sbonaretti @gianthk and I will take care of the last details.

Best,
Simone

2024-10-24 19:18 UTC, fsantini commented on jupyter/ormir-mids_dcm2structure_qmski.ipynb
The executable filename is still dcm2mbids - can you please change it to dcm2omids?

2024-10-24 19:19 UTC, fsantini requested changes
Please change the executable name in the ormir-mids_dcm2structure_qmski.ipynb file

2024-10-25 07:53 UTC, simoneponcioni commented on jupyter/ormir-mids_dcm2structure_qmski.ipynb
Thanks for the good catch, I should have updated it everywhere now

2024-10-26 14:21 UTC, fsantini approved these changes

2024-10-26 14:22 UTC, merged